ALTER TABLE extracted_clips
  ADD COLUMN IF NOT EXISTS qa_status VARCHAR(20) NOT NULL DEFAULT 'not_reviewed',
  ADD COLUMN IF NOT EXISTS qa_score INTEGER,
  ADD COLUMN IF NOT EXISTS qa_feedback TEXT,
  ADD COLUMN IF NOT EXISTS qa_retry_hint TEXT;

ALTER TABLE manual_clipping_clips
  ADD COLUMN IF NOT EXISTS qa_status VARCHAR(20) NOT NULL DEFAULT 'not_reviewed',
  ADD COLUMN IF NOT EXISTS qa_score INTEGER,
  ADD COLUMN IF NOT EXISTS qa_feedback TEXT,
  ADD COLUMN IF NOT EXISTS qa_retry_hint TEXT;
