// Dynamic tool selection for optimized AI agent performance
// Reduces schema complexity by selecting only relevant tools based on context

use std::collections::HashSet;

/// Tool categories for video editing tasks
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ToolCategory {
    CoreEditing,        // trim, merge, split, crop, rotate, etc.
    VisualEffects,      // overlays, filters, color adjustment
    AudioProcessing,    // volume, audio extraction/addition
    AIGeneration,       // TTS, sound effects, music, image generation
    SceneGeneration,    // Blender / Manim / LaTeX / UI mockup renders
    StockMedia,         // Pexels integration
    AnalysisReview,     // Video/image analysis, review
    YouTubeIntegration, // YouTube optimization and trends
    PlatformExport,     // Export and final answer tools
    WorkflowRecipes,    // Multi-step named chains (youtube_ready, podcast_cleanup, etc.)
}

impl ToolCategory {
    /// Get all tool names in this category
    pub fn tools(&self) -> Vec<&'static str> {
        match self {
            ToolCategory::CoreEditing => vec![
                "trim_video",
                "merge_videos",
                "split_video",
                "crop_video",
                "rotate_video",
                "flip_video",
                "resize_video",
                "scale_video",
                "convert_format",
                "compress_video",
                "stabilize_video",
                "stabilize_video_2pass",
                "deinterlace_video",
                "reverse_video",
                "loop_video",
                "minterpolate",
                "convert_framerate",
                "deshake_video",
                "decimate_frames",
                "encode_vp9",
                "encode_av1",
                "encode_hevc",
                "encode_opus",
                "encode_hdr10",
                "encode_nvenc",
                "encode_vaapi",
                "encode_qsv",
                "encode_prores",
                "encode_dnxhd",
                "encode_gif",
                "encode_webm",
                "segment_video",
                "pad_video_time",
                "apply_rotate_angle",
                "create_test_pattern",
            ],
            ToolCategory::VisualEffects => vec![
                "add_text_overlay",
                "add_overlay",
                "apply_filter",
                "adjust_color",
                "picture_in_picture",
                "chroma_key",
                "split_screen",
                "add_subtitles",
                "create_thumbnail",
                "add_transition",
                "add_animated_text",
                "apply_filter_chain",
                "create_thumbnail_hd",
                "adjust_hue",
                "color_balance",
                "normalize_video",
                "apply_lut",
                "denoise_video",
                "unsharp_mask",
                "reduce_noise",
                "pad_video",
                "blend_videos",
                "stack_videos",
                "add_vignette",
                "draw_box",
                "zoompan",
                "adjust_curves",
                "adjust_levels",
                "split_tone",
                "convert_colorspace",
                "apply_tonemap",
                "correct_perspective",
                "correct_lens",
                "apply_shear",
                "blend_frames",
                "temporal_median",
                "tile_frames",
                "adjust_color_temperature",
                "adjust_vibrance",
                "remove_flicker",
                "denoise_video_bm3d",
                "analyze_vectorscope",
                "analyze_waveform",
                "draw_grid",
                "grid_stack_videos",
                "luma_key",
                "displace_video",
                "denoise_video_owden",
                "despill_video",
                "remap_pixels",
                "adjust_exposure",
                "detect_objects_dnn",
                "classify_frames_dnn",
                "upscale_super_resolution",
                "remove_rain_ai",
                "apply_edgedetect",
                "zoom_pan",
                "chromatic_aberration",
                "temporal_blend",
                "motion_interpolate",
                "correct_lens_simple",
                "deinterlace_yadif",
                "correct_perspective_linear",
                "colorize_video",
                "denoise_hqdn3d",
                "select_frames",
                "posterize_video",
                "solarize_video",
                "apply_dilation",
                "apply_erosion",
                "apply_median_filter",
                "apply_histogram_eq",
                "apply_clahe",
                "apply_deblock",
                "adjust_hue_saturation",
                "apply_convolution",
                "apply_gaussian_blur",
                "apply_box_blur",
                "apply_smart_blur",
                "add_film_grain",
                "apply_geq",
                "apply_colorchannelmixer",
                "apply_atadenoise",
                "apply_vaguedenoiser",
                "apply_fftdnoiz",
                "apply_lut3d",
                "measure_siti",
                "apply_amplify",
                "apply_negate",
                "apply_pixelize",
                "apply_colorlevels",
                "apply_pseudocolor",
                "apply_colorhold",
                "apply_shuffleplanes",
                "apply_vstack",
                "apply_hstack",
                "apply_setdar",
                "apply_stereo3d",
                "apply_telecine",
                "apply_pullup",
                "select_thumbnail_frame",
                "apply_threshold",
                "apply_maskedclamp",
                "apply_roberts",
                "apply_sobel",
                "apply_prewitt",
                "apply_kirsch",
                "apply_video_limiter",
                "apply_bilateral",
                "apply_unsharp_mask",
                "apply_lagfun",
                "apply_tinterlace",
                "apply_datascope",
                "apply_fspp",
                "scale_to_reference",
                "apply_fieldorder",
                "optimize_gif_palette",
                "apply_hsv_key",
                "apply_lut_yuv",
                "apply_freezeframes",
                "draw_signal_graph",
                "measure_video_entropy",
                "extract_alpha_channel",
                "merge_alpha_channel",
                "apply_framestep",
                "apply_swaprect",
                "apply_fillborders",
                "apply_chromanr",
                "apply_weave",
                "apply_interlace",
                "apply_xfade_transition",
                "apply_color_key",
                "apply_monochrome",
                "apply_maskedmerge",
                "convert_360_video",
                "fix_banding",
                "apply_greyedge",
                "apply_fade_video",
                "apply_colormatrix",
                "apply_chromashift",
                "apply_cas",
                "apply_nlmeans_video",
                "apply_spp",
                "apply_pp",
                "apply_mestimate",
                "apply_midequalizer",
                "apply_median_spatial",
                "stabilize_video_2pass",
                "apply_lut_rgb",
                "apply_hsvhold",
                "convert_pixel_format",
                "apply_setsar",
                "apply_random_frames",
                "visualize_cqt",
                "visualize_frequencies",
                "edit_image",
            ],
            ToolCategory::AudioProcessing => vec![
                "adjust_volume",
                "extract_audio",
                "add_audio",
                "fade_audio",
                "add_voiceover_to_video",
                "adjust_speed",
                "apply_audio_effect",
                "compress_audio",
                "normalize_audio",
                "equalize_audio",
                "gate_audio",
                "denoise_audio",
                "filter_highpass",
                "filter_lowpass",
                "adjust_bass",
                "adjust_treble",
                "audio_compand",
                "add_audio_delay",
                "add_phaser",
                "remove_clicks",
                "restore_clipping",
                "remove_silence",
                "adjust_stereo_width",
                "apply_stereo_widen",
                "mix_audio_channels",
                "measure_lufs",
                "parametric_eq",
                "audio_limiter",
                "reduce_sibilance",
                "denoise_speech_rnn",
                "render_binaural",
                "add_vibrato",
                "add_tremolo",
                "add_flanger",
                "denoise_audio_nlm",
                "shift_audio_frequency",
                "apply_audio_pulsator",
                "enhance_dialogue",
                "split_audio_channels",
                "map_audio_channels",
                "merge_audio_inputs",
                "apply_crossfeed",
                "apply_extrastereo",
                "apply_firequalizer",
                "apply_biquad",
                "filter_bandpass",
                "filter_bandreject",
                "boost_sub_bass",
                "add_echo",
                "noise_gate",
                "compress_dynamics",
                "add_chorus",
                "widen_stereo",
                "normalize_speech",
                "remove_silence_simple",
                "soft_clip_audio",
                "reverse_audio",
                "blend_audio_streams",
                "measure_audio_spectrum",
                "generate_waveform_video",
                "apply_haas",
                "apply_aemphasis",
                "apply_compensation_delay",
                "apply_earwax",
                "apply_allpass_filter",
                "apply_highshelf",
                "apply_lowshelf",
                "apply_surround_upmix",
                "detect_volume_levels",
                "denoise_audio_fft",
                "loop_audio",
                "apply_dc_shift",
                "measure_dynamic_range",
                "apply_single_eq_band",
                "apply_stereotools",
                "apply_asetrate",
                "normalize_loudness",
                "dynamic_audio_normalize",
                "resample_audio",
                "trim_audio",
                "apply_crystalizer",
                "multiband_compress",
                "apply_super_equalizer",
                "apply_acrusher",
                "apply_atempo",
                "apply_asetnsamples",
                "apply_apad",
                "apply_asubcut",
                "apply_asupercut",
                "apply_audio_iir",
                "apply_audio_expression",
                "convert_audio_format",
                "apply_cross_correlate",
                "apply_audio_multiply",
                "apply_audio_contrast",
                "decode_hdcd",
            ],
            ToolCategory::AIGeneration => vec![
                "generate_text_to_speech",
                "generate_sound_effect",
                "generate_music",
                "generate_image",
                "edit_image",
                "generate_video_script",
                "auto_generate_video",
                "generate_video_queries",
                "analyze_pexels_thumbnail",
            ],
            ToolCategory::SceneGeneration => vec![
                "run_director",
                "blender_generate_scene",
                "blender_generate_data_viz",
                "blender_generate_lower_third",
                "blender_generate_latex",
                "blender_generate_ui_mockup",
                "blender_generate_animation",
                "blender_generate_flowchart",
                "blender_generate_3d_math",
                "blender_generate_code_animation",
                "blender_generate_timeline",
                "blender_generate_network_graph",
                "blender_generate_logo_reveal",
                "blender_generate_abstract_bg",
                "blender_generate_countdown",
                "blender_generate_text_animation",
                "blender_generate_vector_field",
                "blender_generate_matrix_transform",
                "blender_generate_polar_graph",
                "blender_generate_geometry_proof",
                "blender_generate_physics_sim",
                "blender_generate_rigid_body_drop",
                "blender_generate_camera_path",
                "blender_generate_toon_scene",
                "blender_generate_ui_demo",
                "blender_generate_geometry_scatter",
            ],
            ToolCategory::StockMedia => vec![
                "pexels_search",
                "pexels_download_video",
                "pexels_download_photo",
                "pexels_get_trending",
                "pexels_get_curated",
                "sketchfab_search",
                "sketchfab_get_model",
                "sketchfab_download",
                "create_blank_video",
                "generate_video_queries",
                "analyze_pexels_thumbnail",
            ],
            ToolCategory::AnalysisReview => vec![
                "analyze_video",
                "analyze_image",
                "view_video",
                "review_video",
                "view_image",
                "extract_frames",
                "get_video_duration",
                "detect_scene_changes",
                "measure_loudness",
                "detect_silence",
                "compare_ssim",
                "compare_psnr",
                "analyze_audio_stats",
                "analyze_video_signal",
                "measure_lufs",
                "analyze_vectorscope",
                "analyze_waveform",
                "measure_vmaf",
                "detect_frozen_frames",
                "measure_silence",
                "measure_siti",
                "detect_black_frames",
                "detect_interlace_type",
                "measure_dynamic_range",
                "measure_video_entropy",
                "detect_volume_levels",
                "verify_clip_quality_tool",
                "run_video_qa",
            ],
            ToolCategory::YouTubeIntegration => vec![
                "optimize_youtube_metadata",
                "analyze_youtube_performance",
                "suggest_content_ideas",
                "search_youtube_trends",
                "search_youtube_channels",
            ],
            ToolCategory::PlatformExport => vec![
                "export_for_platform",
                "export_custom_quality",
                "submit_final_answer",
                "set_chat_title",
            ],
            ToolCategory::WorkflowRecipes => vec![
                "youtube_ready_export",
                "podcast_cleanup",
                "cinematic_grade",
                "create_gif_workflow",
                "talking_head_cleanup",
            ],
        }
    }
}

/// Tool selector that dynamically chooses relevant tools based on user intent
pub struct ToolSelector;

impl ToolSelector {
    /// Select relevant tools based on user prompt
    /// Returns a filtered list of tool names (max 20 tools as per Google's recommendation)
    pub fn select_tools(user_prompt: &str) -> Vec<String> {
        let prompt_lower = user_prompt.to_lowercase();

        // Detect categories based on keywords
        let mut selected_categories = Vec::new();

        // Always include core editing and platform export (essential for all tasks)
        selected_categories.push(ToolCategory::CoreEditing);
        selected_categories.push(ToolCategory::PlatformExport);

        // Visual effects keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "overlay",
                "text",
                "subtitle",
                "filter",
                "color",
                "picture in picture",
                "pip",
                "chroma",
                "green screen",
                "split screen",
                "thumbnail",
                "effect",
                "vignette",
                "hue",
                "lut",
                "denoise",
                "sharpen",
                "zoom",
                "pan",
                "pad",
                "curves",
                "levels",
                "tone",
                "perspective",
                "lens",
                "shear",
                "temporal",
                "tile",
                "tonemap",
                "colorspace",
                "temperature",
                "white balance",
                "warm",
                "cool",
                "vibrance",
                "vivid",
                "flicker",
                "bm3d",
                "vectorscope",
                "waveform",
                "scope",
                "grid",
                "xstack",
                "luma key",
                "lumakey",
                "luma_key",
                "stack video",
                "displace",
                "warp",
                "distort",
                "remap",
                "despill",
                "spill",
                "wavelet",
                "owden",
                "exposure",
                "ev stop",
                "object detect",
                "dnn detect",
                "yolo",
                "bounding box",
                "classify",
                "dnn classify",
                "image class",
                "super resolution",
                "upscale",
                "sr filter",
                "ai upscal",
                "derain",
                "rain remov",
                "rain streak",
                "edge detect",
                "edgedetect",
                "canny",
                "outline",
                "ken burns",
                "zoom pan",
                "zoompan",
                "pan and zoom",
                "vignette",
                "lens shading",
                "darken edges",
                "chromatic aberration",
                "lens fringe",
                "rgb shift",
                "temporal blend",
                "frame blend",
                "motion blur tblend",
                "frame interpolat",
                "slow motion",
                "minterpolat",
                "smooth slow",
                "lens correct",
                "barrel distort",
                "pincushion",
                "fisheye correct",
                "deinterlac",
                "interlac",
                "yadif",
                "perspective correct",
                "keystone",
                "trapezoid",
                "colorize",
                "colour tint",
                "sepia",
                "tint grey",
                "hqdn3d",
                "3d denois",
                "select frame",
                "keyframe extract",
                "sample frame",
                "every nth frame",
                "posterize",
                "poster effect",
                "colour level",
                "graphic novel",
                "solarize",
                "invert pixel",
                "psychedelic",
                "dilation",
                "dilate",
                "morpholog",
                "expand bright",
                "erosion",
                "erode",
                "shrink bright",
                "median filter",
                "salt pepper",
                "median noise",
                "histogram eq",
                "histeq",
                "contrast stretch",
                "clahe",
                "adaptive histogram",
                "local contrast",
                "deblock",
                "block artefact",
                "dct artefact",
                "macroblocking",
                "hue saturation",
                "huesaturation",
                "saturation adjust",
                "convolution",
                "kernel",
                "custom filter",
                "sharpen kernel",
                "blur kernel",
                "emboss",
                "gaussian blur",
                "gblur",
                "soft blur",
                "background blur",
                "box blur",
                "avgblur",
                "rectangular blur",
                "smart blur",
                "smartblur",
                "edge preserv blur",
                "film grain",
                "grain",
                "analog noise",
                "noise filter",
                "film texture",
                "geq",
                "pixel equation",
                "per pixel",
                "pixel formula",
                "channel mixer",
                "colorchannelmixer",
                "channel swap",
                "cross process",
                "atadenoise",
                "temporal averaging",
                "adaptive temporal",
                "vaguedenoiser",
                "wavelet denois",
                "fftdnoiz",
                "fft denois",
                "frequency denois",
                "lut3d",
                "3d lut",
                "cube lut",
                ".cube",
                "amplify",
                "motion amplif",
                "temporal amplif",
                "rotate angle",
                "arbitrary rotat",
                "free rotat",
                "negate",
                "invert color",
                "invert video",
                "negative",
                "pixelize",
                "pixelat",
                "mosaic",
                "censor blur",
                "pixelise",
                "color level",
                "input level",
                "output level",
                "black point",
                "white point",
                "pseudocolor",
                "false color",
                "heat map",
                "heatmap",
                "color hold",
                "colorhold",
                "isolate color",
                "selective color",
                "shuffle plane",
                "shuffleplane",
                "channel order",
                "swap channel",
                "vertical stack",
                "vstack",
                "stack vertical",
                "horizontal stack",
                "hstack",
                "stack horizontal",
                "side by side",
                "aspect ratio",
                "setdar",
                "display ratio",
                "dar",
                "stereo 3d",
                "stereo3d",
                "3d conversion",
                "anaglyph",
                "side by side 3d",
                "telecine",
                "film cadence",
                "3:2 pulldown",
                "pullup",
                "inverse telecine",
                "ivtc",
                "remove pulldown",
                "thumbnail",
                "best frame",
                "thumbnail frame",
                "poster frame",
                "threshold",
                "pixel threshold",
                "clip pixel",
                "binary video",
                "maskedclamp",
                "masked clamp",
                "pixel clamp",
                "roberts",
                "roberts edge",
                "cross edge detect",
                "sobel",
                "sobel edge",
                "gradient detect",
                "prewitt",
                "prewitt edge",
                "kirsch",
                "kirsch edge",
                "compass edge",
                "video limiter",
                "signal limit",
                "broadcast legal",
                "legal range",
                "bilateral",
                "bilateral filter",
                "edge preserving",
                "skin smooth",
                "unsharp mask",
                "unsharp",
                "precise sharpen",
                "lagfun",
                "ghost trail",
                "motion trail",
                "lag fun",
                "tinterlace",
                "temporal interlace",
                "broadcast interlace",
                "datascope",
                "pixel data",
                "colour accuracy",
                "qc scope",
                "fspp",
                "fast super pixel",
                "frequency denois",
                "scale2ref",
                "scale to reference",
                "match resolution",
                "match dimensions",
                "fieldorder",
                "field order",
                "tff",
                "bff",
                "top field",
                "bottom field",
                "gif palette",
                "optimize gif",
                "palettegen",
                "paletteuse",
                "high quality gif",
                "animated gif",
                "hsv key",
                "hsvkey",
                "hsv keying",
                "hue key",
                "lutyuv",
                "lut yuv",
                "yuv expression",
                "per pixel yuv",
                "freezeframes",
                "freeze frame",
                "freeze video",
                "pause frame",
                "signal graph",
                "drawgraph",
                "signalstats",
                "luma graph",
                "video graph",
                "video entropy",
                "frame complexity",
                "entropy measure",
                "alpha channel",
                "alphaextract",
                "transparency mask",
                "extract transparency",
                "alphamerge",
                "merge alpha",
                "add transparency",
                "alpha mask",
                "framestep",
                "frame step",
                "every nth frame",
                "time lapse from",
                "swaprect",
                "swap rect",
                "swap region",
                "swap area",
                "fillborders",
                "fill border",
                "fill edge",
                "smear edge",
                "mirror border",
                "extend border",
                "chromanr",
                "chroma noise",
                "colour noise",
                "color noise reduc",
                "weave",
                "weave fields",
                "reconstruct interlace",
                "create interlac",
                "progressive to interlac",
                "interlace output",
                "xfade",
                "cross fade",
                "crossfade",
                "transition effect",
                "dissolve transition",
                "wipe transition",
                "color key",
                "colorkey",
                "colour key",
                "flat background key",
                "monochrome",
                "black and white",
                "b&w",
                "b&w filter",
                "mono video",
                "greyscale video",
                "maskedmerge",
                "masked merge",
                "mask composite",
                "alpha mask blend",
                "360 video",
                "v360",
                "equirectangular",
                "360 convert",
                "vr video",
                "360 projection",
                "banding",
                "colour banding",
                "gradient band",
                "gradfun",
                "dither gradient",
                "fix bands",
                "greyedge",
                "grey edge",
                "grey world",
                "auto white balance",
                "colour cast fix",
                "fade video",
                "video fade in",
                "video fade out",
                "fade from black",
                "fade to black",
                "colormatrix",
                "color matrix",
                "bt601",
                "bt709",
                "bt2020",
                "color standard",
                "color space convert",
                "chromashift",
                "chroma shift",
                "chroma offset",
                "colour fringe",
                "colour shift",
                "cas",
                "contrast adaptive sharpening",
                "adaptive sharp",
                "nlmeans",
                "nl means",
                "non local means",
                "patch denois",
                "spp",
                "simple post process",
                "dct denois",
                "block denois",
                "pp",
                "post process",
                "dering",
                "deblock pp",
                "postproc",
                "mestimate",
                "motion estimate",
                "mv estimate",
                "motion vector",
                "midequalizer",
                "mid equalizer",
                "midtone equal",
                "dual input equal",
                "median spatial",
                "spatial median",
                "percentile filter",
                "robust median",
                "two pass stabiliz",
                "vidstab",
                "accurate stabiliz",
                "pass stabiliz",
                "lut rgb",
                "rgb lut",
                "rgb expression",
                "pixel expression",
                "lutrgb",
                "hsvhold",
                "hsv hold",
                "selective color",
                "color hold",
                "keep one color",
                "isolate color",
                "pixel format",
                "convert format",
                "pix fmt",
                "yuv420p",
                "yuv444p",
                "nv12",
                "p010le",
                "sample aspect",
                "setsar",
                "anamorphic",
                "sar fix",
                "par fix",
                "random frames",
                "scramble frames",
                "glitch frame",
                "frame glitch",
                "cqt",
                "constant q transform",
                "showcqt",
                "musical spectrum",
                "showfreqs",
                "frequency chart",
                "freq visualization",
                "frequency bar",
                // Natural language style requests
                "vintage",
                "retro",
                "old film",
                "look old",
                "look vintage",
                "aged",
                "make it look",
                "cinematic look",
                "film look",
                "movie look",
                "horror look",
                "cyberpunk",
                "neon",
                "sci-fi look",
                "futuristic",
                "warm look",
                "cool look",
                "teal and orange",
                "colour grade",
                "color grade",
                // Captions and subtitles
                "caption",
                "auto caption",
                "auto subtitle",
                "closed caption",
                ".srt",
                "srt file",
                "burn subtitle",
                "burn caption",
                "hardcode sub",
                "hardcode caption",
                // Vertical/short-form
                "vertical",
                "portrait video",
                "tiktok",
                "reels",
                "shorts",
                "9:16",
                "square video",
                "1:1",
                // Stabilization natural language
                "shaky cam",
                "shaky video",
                "wobbly",
                "hand held",
                "handheld",
                "gopro",
                "action cam",
                "drone footage",
                // Image editing
                "edit image",
                "modify image",
                "image edit",
                "transform image",
                "change image",
                "image overlay",
                "frame edit",
                "image style",
                "edit the image",
                "modify the image",
                "update the image",
            ],
        ) {
            selected_categories.push(ToolCategory::VisualEffects);
        }

        // Core editing keywords (including deshake, decimate, codec encoding)
        if Self::contains_any(
            &prompt_lower,
            &[
                "shake",
                "shaky",
                "handheld",
                "deshake",
                "stabiliz",
                "decimate",
                "duplicate frame",
                "telecine",
                "vp9",
                "av1",
                "hevc",
                "h.265",
                "h265",
                "x265",
                "libx265",
                "hdr10",
                "hdr",
                "mastering display",
                "maxcll",
                "nvenc",
                "nvidia",
                "cuda",
                "gpu encode",
                "vaapi",
                "quick sync",
                "qsv",
                "intel gpu",
                "prores",
                "dnxhd",
                "dnxhr",
                "avid",
                "apple intermediate",
                "animated gif",
                "encode gif",
                "palette",
                "webm",
                "vp8",
                "opus encode",
                "hardware encod",
                "hw encod",
                "segment video",
                "split video chunk",
                "split into parts",
                "pad video",
                "add black frames",
                "add padding",
                "test pattern",
                "smpte bar",
                "colour bar",
                "smptebars",
                "testsrc",
                "test card",
                // Format/codec natural language
                "convert to",
                "change format",
                "export as",
                "save as",
                "output format",
                "mp4",
                "mov",
                "mkv",
                "avi",
                "webm",
                "flv",
                "wmv",
                "h264",
                "h.264",
                "x264",
                "libx264",
                "aac",
                "mp3 to",
                "make it smaller",
                "reduce file size",
                "smaller file",
                // Speed / time
                "speed up",
                "slow down",
                "time lapse",
                "timelapse",
                "hyperlapse",
                "frame rate",
                "fps",
                "24fps",
                "30fps",
                "60fps",
            ],
        ) {
            selected_categories.push(ToolCategory::CoreEditing);
        }

        // Audio processing keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "audio",
                "sound",
                "volume",
                "music",
                "voiceover",
                "voice",
                "mute",
                "extract audio",
                "add audio",
                "fade",
                "speed",
                "slow",
                "fast",
                "compress",
                "normalize",
                "equaliz",
                "gate",
                "noise",
                "highpass",
                "lowpass",
                "bass",
                "treble",
                "delay",
                "phaser",
                "click",
                "clipping",
                "stereo",
                "pan",
                "widen",
                "silence remove",
                "lufs",
                "loudness",
                "broadcast",
                "parametric",
                "limiter",
                "limit peak",
                "sibilance",
                "ess",
                "de-ess",
                "deess",
                "neural",
                "rnn",
                "speech denoise",
                "binaural",
                "headphone",
                "vibrato",
                "tremolo",
                "flanger",
                "nlm",
                "anlmdn",
                "frequency shift",
                "afreqshift",
                "pulsator",
                "pulse",
                "dialogue enhance",
                "channel split",
                "channel map",
                "amerge",
                "crossfeed",
                "extrastereo",
                "firequalizer",
                "biquad",
                "bandpass",
                "bandreject",
                "notch",
                "sub bass",
                "asubboost",
                "echo",
                "reverb",
                "aecho",
                "delay effect",
                "noise gate",
                "agate",
                "gate audio",
                "dynamic range",
                "compressor",
                "acompressor",
                "compress audio",
                "chorus",
                "shimmer",
                "double voice",
                "stereo widen",
                "stereowiden",
                "widen sound",
                "speech normali",
                "speechnorm",
                "remove silence",
                "silenceremove",
                "cut silence",
                "soft clip",
                "asoftclip",
                "saturat peak",
                "reverse audio",
                "backwards audio",
                "areverse",
                "mix audio",
                "blend audio",
                "amix",
                "combine audio",
                "silence detect",
                "find silence",
                "silence timestamp",
                "silencedetect",
                "spectrum",
                "showspectrum",
                "frequency visual",
                "audio visual",
                "haas",
                "haas effect",
                "stereo delay",
                "spatial width",
                "aemphasis",
                "de-emphasis",
                "pre-emphasis",
                "riaa",
                "vinyl eq",
                "fm emphasis",
                "compensationdelay",
                "compensation delay",
                "mic alignment",
                "microphone delay",
                "time align",
                "earwax",
                "ear wax",
                "headphone 3d",
                "immersive headphone",
                "allpass",
                "all pass",
                "phase shift",
                "phase correction",
                "high shelf",
                "highshelf",
                "shelf boost high",
                "air frequency",
                "treble shelf",
                "low shelf",
                "lowshelf",
                "shelf boost low",
                "bass shelf",
                "warmth shelf",
                "surround upmix",
                "5.1 upmix",
                "7.1 upmix",
                "stereo to surround",
                "upmix surround",
                "volumedetect",
                "volume detect",
                "peak volume",
                "mean volume",
                "max volume",
                "afftdn",
                "fft denoise",
                "fft noise",
                "background noise",
                "room tone",
                "hum remov",
                "loop audio",
                "aloop",
                "repeat audio",
                "extend music",
                "dc shift",
                "dcshift",
                "dc offset",
                "dc bias",
                "dynamic range meter",
                "drmeter",
                "dr meter",
                "crest factor",
                "single band eq",
                "equalizer band",
                "one band",
                "targeted eq",
                "stereotools",
                "stereo tools",
                "ms matrix",
                "mid side",
                "phase invert channel",
                "asetrate",
                "set rate",
                "pitch tape",
                "chipmunk",
                "slowed reverb",
                "tape speed",
                "loudnorm",
                "loudness normalize",
                "ebu r128",
                "lufs normalize",
                "broadcast standard",
                "streaming loudness",
                "dynaudnorm",
                "dynamic normaliz",
                "per frame normal",
                "level dialogue",
                "resample audio",
                "aresample",
                "sample rate convert",
                "44100",
                "48000",
                "sample rate",
                "trim audio",
                "atrim",
                "audio trim",
                "cut audio stream",
                "crystalizer",
                "crystal",
                "audio enhance",
                "transient enhance",
                "mcompand",
                "multiband",
                "multi band compress",
                "frequency compress",
                "superequalizer",
                "super eq",
                "18 band",
                "graphic eq",
                "acrusher",
                "bit crush",
                "bit depth reduce",
                "lo-fi",
                "lofi",
                "distort audio",
                "crush audio",
                "atempo",
                "audio tempo",
                "time stretch",
                "pitch preserve",
                "speed audio",
                "asetnsamples",
                "set samples",
                "audio chunk",
                "sample block",
                "apad",
                "audio pad",
                "pad audio",
                "silence pad",
                "audio silence end",
                "asubcut",
                "sub cut",
                "subsonic",
                "infrasound",
                "dc offset",
                "dc block",
                "asupercut",
                "super cut",
                "ultrasonic",
                "ultrasound cut",
                "nyquist",
                "aiir",
                "iir filter",
                "infinite impulse",
                "digital filter",
                "custom filter",
                "aeval",
                "audio expression",
                "per sample",
                "sample math",
                "audio formula",
                "aformat",
                "audio format",
                "sample format",
                "convert audio",
                "audio layout",
                "channel layout",
                "axcorrelate",
                "cross correlate",
                "audio correlate",
                "signal correlate",
                "alignment detect",
                "amultiply",
                "audio multiply",
                "ring modulation",
                "ring mod",
                "metallic audio",
                "robotic voice",
                "acontrast",
                "audio contrast",
                "audio punch",
                "loudness enhance",
                "tape saturation",
                "hdcd",
                "high definition compatible",
                "hdcd decode",
                "hdcd master",
                "peak extend",
            ],
        ) {
            selected_categories.push(ToolCategory::AudioProcessing);
        }

        // Analysis keywords (including lufs, vectorscope, waveform, vmaf)
        if Self::contains_any(
            &prompt_lower,
            &[
                "lufs",
                "ebu",
                "r128",
                "broadcast loudness",
                "vectorscope",
                "waveform monitor",
                "scope",
                "signal level",
                "vmaf",
                "perceptual quality",
                "quality score",
                "frozen frame",
                "freeze detect",
                "stuck frame",
                "freeze event",
                "black frame",
                "black scene",
                "detect black",
                "blank frame",
                "blackdetect",
                "interlace detect",
                "interlaced",
                "interlac type",
                "progressive detect",
                "idet",
                "silence detect",
                "find silence",
                "silence region",
                "silencedetect",
                "spectrum analysis",
                "frequency content",
                "showspectrum",
                "siti",
                "spatial information",
                "temporal information",
                "si ti",
                "waveform video",
                "showwaves",
                "audio waveform",
            ],
        ) {
            selected_categories.push(ToolCategory::AnalysisReview);
        }

        // AI generation keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "generate",
                "create",
                "tts",
                "text to speech",
                "sound effect",
                "background music",
                "script",
                "auto",
                "ai",
                "artificial",
                "edit image",
                "modify image",
                "image edit",
                "transform image",
                "ai image",
            ],
        ) {
            selected_categories.push(ToolCategory::AIGeneration);
        }

        // Blender / Manim / LaTeX / motion-generation keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "blender",
                "manim",
                "latex",
                "equation",
                "math animation",
                "math video",
                "scene generation",
                "3d scene",
                "3d animation",
                "ui mockup",
                "device mockup",
                "data viz",
                "data visualization",
                "flowchart",
                "timeline",
                "network graph",
                "logo reveal",
                "countdown",
                "camera path",
                "toon scene",
                "physics sim",
                "landing page animation",
                "website animation",
                "animated explainer",
                "motion graphic",
                "motion graphics",
                "render scene",
                "render animation",
            ],
        ) {
            selected_categories.push(ToolCategory::SceneGeneration);
        }

        // Stock media keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "pexels",
                "stock",
                "footage",
                "photo",
                "image",
                "download",
                "trending",
                "curated",
                "blank video",
                "template",
            ],
        ) {
            selected_categories.push(ToolCategory::StockMedia);
        }

        // Analysis & review keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "analyze",
                "analysis",
                "review",
                "check",
                "inspect",
                "view",
                "metadata",
                "information",
                "details",
                "frames",
                "extract frame",
                "duration",
                "loudness",
                "silence",
                "scene",
                "ssim",
                "psnr",
                "quality",
                "signal",
                "stats",
            ],
        ) {
            selected_categories.push(ToolCategory::AnalysisReview);
        }

        // YouTube integration keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "youtube",
                "yt",
                "optimize",
                "seo",
                "metadata",
                "performance",
                "trends",
                "trending",
                "viral",
                "channel",
                "content ideas",
            ],
        ) {
            selected_categories.push(ToolCategory::YouTubeIntegration);
        }

        // Workflow recipe keywords
        if Self::contains_any(
            &prompt_lower,
            &[
                "workflow",
                "recipe",
                "pipeline",
                "youtube ready",
                "youtube-ready",
                "ready for youtube",
                "ready to upload",
                "ready to post",
                "podcast",
                "cleanup",
                "clean up",
                "cinematic",
                "film look",
                "talking head",
                "talking-head",
                "webcam",
                "presenter",
                "zoom recording",
                "create gif",
                "make gif",
                "gif",
                "all in one",
                "all-in-one",
                "one step",
                "one-step",
                "stabilize and",
                "denoise and",
                "grade and",
                "quick export",
                "professional look",
                "broadcast ready",
            ],
        ) {
            selected_categories.push(ToolCategory::WorkflowRecipes);
        }

        // Collect all tools from selected categories
        let mut tools = HashSet::new();
        for category in &selected_categories {
            for tool in category.tools() {
                tools.insert(tool.to_string());
            }
        }

        // No arbitrary cap — pass all matched tools to the AI.
        // Claude and Gemini comfortably handle 200+ tool schemas; the old
        // 20-tool limit was written when we had ~35 tools and would silently
        // hide 280+ tools from the model with the current 320-tool suite.
        let mut tool_list: Vec<String> = tools.into_iter().collect();
        tool_list.sort(); // Sort for consistency

        // Catch-all: if nothing matched beyond the always-included categories,
        // return a curated set of the ~25 most universally-needed tools instead of
        // all 320. Sending 320 tools to Gemini hits the "too many schema states"
        // INVALID_ARGUMENT error (see https://github.com/googleapis/python-genai/issues/660).
        // The general set covers 90%+ of real user requests without schema overflow.
        if tool_list.len()
            <= ToolCategory::CoreEditing.tools().len() + ToolCategory::PlatformExport.tools().len()
        {
            tracing::info!(
                "No specific category matched — returning general-purpose tool set (catch-all)"
            );
            return Self::general_tools();
        }

        tracing::info!(
            "Dynamic tool selection: {} categories, {} tools selected",
            selected_categories.len(),
            tool_list.len()
        );

        tool_list
    }

    /// Helper function to check if text contains any of the keywords
    fn contains_any(text: &str, keywords: &[&str]) -> bool {
        keywords.iter().any(|keyword| text.contains(keyword))
    }

    /// Curated set of ~25 most universally-needed tools for general requests.
    /// Used when no specific category matches, keeping Gemini schema within safe limits.
    pub fn general_tools() -> Vec<String> {
        vec![
            // Core editing (most common operations)
            "trim_video".into(),
            "merge_videos".into(),
            "split_video".into(),
            "crop_video".into(),
            "rotate_video".into(),
            "resize_video".into(),
            "convert_format".into(),
            "compress_video".into(),
            "reverse_video".into(),
            // Visual
            "add_text_overlay".into(),
            "apply_filter".into(),
            "adjust_color".into(),
            "create_thumbnail".into(),
            "add_subtitles".into(),
            // Audio
            "extract_audio".into(),
            "add_audio".into(),
            "adjust_volume".into(),
            "denoise_audio".into(),
            // AI generation
            "auto_generate_video".into(),
            "generate_image".into(),
            "generate_text_to_speech".into(),
            "generate_music".into(),
            "run_director".into(),
            "blender_generate_scene".into(),
            "blender_generate_animation".into(),
            "blender_generate_latex".into(),
            "blender_generate_ui_mockup".into(),
            "set_chat_title".into(),
            "submit_final_answer".into(),
            // Stock media
            "search_pexels_videos".into(),
            "download_pexels_video".into(),
            // Analysis
            "analyze_video".into(),
            // Export
            "export_for_platform".into(),
        ]
    }

    /// Get all available tools (for backwards compatibility or fallback)
    pub fn all_tools() -> Vec<String> {
        let all_categories = vec![
            ToolCategory::CoreEditing,
            ToolCategory::VisualEffects,
            ToolCategory::AudioProcessing,
            ToolCategory::AIGeneration,
            ToolCategory::SceneGeneration,
            ToolCategory::StockMedia,
            ToolCategory::AnalysisReview,
            ToolCategory::YouTubeIntegration,
            ToolCategory::PlatformExport,
            ToolCategory::WorkflowRecipes,
        ];

        let mut tools = HashSet::new();
        for category in all_categories {
            for tool in category.tools() {
                tools.insert(tool.to_string());
            }
        }

        let mut tool_list: Vec<String> = tools.into_iter().collect();
        tool_list.sort();
        tool_list
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_editing_prompt() {
        let tools = ToolSelector::select_tools("trim my video from 0:10 to 0:30");
        assert!(tools.contains(&"trim_video".to_string()));
        assert!(!tools.is_empty());
    }

    #[test]
    fn test_audio_prompt() {
        let tools = ToolSelector::select_tools("add background music to my video");
        assert!(tools.contains(&"add_audio".to_string()));
        assert!(!tools.is_empty());
    }

    #[test]
    fn test_complex_prompt() {
        let tools = ToolSelector::select_tools(
            "create a video with text overlay, background music, and upload to YouTube",
        );
        assert!(tools.contains(&"add_text_overlay".to_string()));
        assert!(tools.contains(&"add_audio".to_string()));
    }

    #[test]
    fn test_visual_effects_triggers() {
        let tools = ToolSelector::select_tools("make the video look cinematic with film grain");
        assert!(tools.contains(&"add_film_grain".to_string()));
    }

    #[test]
    fn test_workflow_recipe_trigger() {
        let tools = ToolSelector::select_tools("make it youtube ready");
        assert!(tools.contains(&"youtube_ready_export".to_string()));
    }

    #[test]
    fn test_stabilize_trigger() {
        let tools = ToolSelector::select_tools("stabilize my shaky footage");
        assert!(tools.contains(&"stabilize_video_2pass".to_string()));
    }

    #[test]
    fn test_all_tools() {
        let tools = ToolSelector::all_tools();
        assert!(tools.len() > 300); // Should have all 320+ tools
    }

    #[test]
    fn test_catch_all_on_unknown_prompt() {
        // An unrecognised prompt should return all tools rather than a tiny set
        let tools = ToolSelector::select_tools("do something creative with my video");
        assert!(tools.len() > 100, "Catch-all should return all tools");
    }
}
